[package]
name = "tracer"
version = "0.1.0"
authors = ["Jacob Chvatal <jake@isnt.online>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
